name: Deploy External Backend to Cloud Run

on:
  workflow_dispatch:  # Manual trigger from Actions tab

jobs:
  deploy:
    name: Clone External Repo & Deploy to GCP
    runs-on: ubuntu-latest

    steps:
    - name: Clone External Repo
      run: |
        git clone  https://github.com/devlogixteam/Nudged-Backend.git
        cd Nudged-Backend
        echo "Cloned and checked out branch ${{ secrets.CLONE_BRANCH }}"


    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for GCP Artifact Registry
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

    - name: Build Docker Image
      run: |
        cd Nudged-Backend
        VERSION="v1-$(date +%s)"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        docker build -t prod-test:$VERSION .

    - name: Tag Docker Image for Artifact Registry
      run: |
        docker tag prod-test:${{ env.VERSION }} \
          ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/prod-test/prod-test:${{ env.VERSION }}

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/prod-test/prod-test:${{ env.VERSION }}

    - name: List Docker Images (optional)
      run: |
        gcloud artifacts docker images list \
          ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/prod-test

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy prod-test-service \
          --image=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/prod-test/prod-test:${{ env.VERSION }} \
          --platform=managed \
          --region=${{ secrets.GCP_REGION }} \
          --port=8000 \
          --allow-unauthenticated \
          --service-account=your-service-account@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com \
          --quiet
