name: Deploy External Repo to Cloud Run

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Clone & Deploy

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Clone external repo and checkout branch
      run: |
        git clone ${{ secrets.EXTERNAL_REPO }}
        cd Nudged-Backend
        git checkout ${{ secrets.EXTERNAL_BRANCH }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

    - name: Build Docker Image
      run: |
        cd Nudged-Backend
        VERSION=v1-$(date +%Y%m%d%H%M%S)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        docker build -t ${{ secrets.IMAGE_NAME }}:$VERSION .

    - name: Tag Docker Image
      run: |
        docker tag ${{ secrets.IMAGE_NAME }}:${{ env.VERSION }} \
          ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/prod-test/${{ secrets.IMAGE_NAME }}:${{ env.VERSION }}

    - name: Push Docker Image
      run: |
        docker push \
          ${{ secrets.GCP_REGION }}-docker.pkg.dev_
